id = "mcp-server-byterover"
name = "ByteRover MCP Server"
version = "0.0.2"
schema_version = 2
authors = ["Andy <andy@byterover.dev>"]
description = "ByteRover - Agentic Memory Management"
repository = "https://github.com/campfirein/byterover-zed-extension"

[context_servers.mcp-server-byterover]
name = "ByteRover MCP Server"
